CREATE TABLE supplier1 (
  SNO TEXT PRIMARY KEY,
  SNAME TEXT,
  STATUS INTEGER,
  CITY TEXT
  );

INSERT INTO supplier1 (SNO,SNAME,STATUS,CITY) VALUES
('S1','SMITH',20,'LONDON'),
('S2','AARUSH',16,'INDIA'),
('S3','YASH',14,'INDIA'),
('S4','MICHELLE',23,'ARGENTINA'),
('S5','KYLIE',22,'LOS ANGELES');

SELECT * FROM supplier1 ;

SELECT SNAME,CITY FROM supplier1 ;